server:
  port: 9001

spring:
  application:
    name: DEPARTMENT-SERVICE
  jmx:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-register: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    hostname: localhost