server:
  port: 9999

spring:
  application:
    name: ADMIN-SERVER
  security:
    user:
      name: admin
      password: password
  boot:
    admin:
      discovery:
        ignored-services: ADMIN-SERVER
  jmx:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
#info:
#  tags:
#    environment: test
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#      #defaultZone: http://eureka:password@localhost:8761/eureka/