server:
  port: 9002

spring:
  application:
    name: USER-SERVICE
  jmx:
    enabled: true
  zipkin:
    base-url: http://127.0.0.1:9411/

management:
  endpoints:
    web:
      exposure:
        include: "*"
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-register: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    hostname: localhost