server:
  port: 9006

spring:
  application:
    name: POST-SERVICE
  logstash:
    server: logstash
    port: 5000
  logger:
    path: ./log
    name: post-service
  main:
    banner-mode: "off"

comment-service:
  base-url: http://localhost:9006