server:
  port: 9003

spring:
  application:
    name: ORDER-SERVICE
  h2:
    console:
      enabled: true
  zipkin:
    base-url: http://127.0.0.1:9411/
  jmx:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  file: C:/Users/jean.pereira.sampaio/Desktop/microservices.log

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-register: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    hostname: localhost